name = "CollatzLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CollatzLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "64fbe722961f672fe20c1b43539821feedd1f36d"

[[lean_lib]]
name = "CollatzLean"
