import CollatzLean.Collatz2.CSTMicro.MultiCorner.TerminalLastTwoExposedNormalForm
import CollatzLean.Collatz2.CSTMicro.MultiCorner.CarryNormalizedCheckpoint
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RecordFerrersExposedProvenance
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedBranchDivisibility
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedTerminalComponentRigidity
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSingleCornerHenselObligation
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedBranchClosure
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedTwoCornerHensel
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedCarryNormalizedTail
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedCanonicalHenselBridge
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedHenselFactorRepeat
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedHenselZeroCycleBridge
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedHenselNonzeroRepeatObligation
import CollatzLean.Collatz2.CSTMicro.MultiCorner.LeftOfCriticalizationBridge
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselBridge
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselBeattyArithmetic
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselFactorRepeat
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselNonzeroRepeat
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselPrimitiveZeroClosure
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselZeroCycle
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselLargeWidthClosure
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselFinite36
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedCriticalTailFusion
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedRepeatIntervalDefectBridge
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedRightEndSmallness
import CollatzLean.Collatz2.CSTMicro.MultiCorner.RestartedSuffixHenselFinite36
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedShiftedRepeatIntervalDefect
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedTerminalPredFusion
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedTerminalFareyComparison
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedCriticalizationUnitBridge
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedTerminalThreeClearance
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedTerminalTailDepthCoordinates
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedShiftedRepeatStateDifference
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedFreeBaseQOneBound
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedNonzeroRepeatDepthBudget
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedActualTerminalMountain
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedMountainParameterLeftIdentity
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedMountainParameterTerminalInverse
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedActualMountainBridge
/-
# MultiCorner attached Shared-Cost checkpoint umbrella

attached branch の数学的 Shared-Cost 方針をまとめて import する入口。

この段階では attached impossibility 自体は主張しない。
二つの predecessor が共有する `G-q` budget、straight cost transport、
entrance-depth Hensel residue を lossless に保持し、次段の純算術排除定理へ渡す。
-/
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedSharedCostArithmetic
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedSharedCostTransfer
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedEntranceDepthHensel
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedSharedCostCheckpoint
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedSharedCostRhoDepthCompatibility
import CollatzLean.Collatz2.CSTMicro.MultiCorner.ActualAttachedSharedCostPairAssembly
import CollatzLean.Collatz2.CSTMicro.MultiCorner.ActualAttachedDoublePredecessorSafety
--
import CollatzLean.Collatz2.CSTMicro.MultiCorner.AttachedIntervalFerrersDefectBridge



/-!
# CSTMicro MultiCorner

`card E ≥ 2` branch の共通入口。


-/
