import CollatzLean.Collatz2.Core.Word
import CollatzLean.Collatz2.Core.AffineTransfer
import CollatzLean.Collatz2.Core.DisplacementForm
import CollatzLean.Collatz2.Core.TranslationPath
import CollatzLean.Collatz2.Core.Realization
import CollatzLean.Collatz2.Core.Interval

import CollatzLean.Collatz2.Local.DeterminantSign
import CollatzLean.Collatz2.Local.Defect
import CollatzLean.Collatz2.Local.FirstCrossing
import CollatzLean.Collatz2.Local.SuffixDeterminantProfile
import CollatzLean.Collatz2.Local.TranslationDeterminant
import CollatzLean.Collatz2.Local.ContractingClosure

import CollatzLean.Collatz2.Orbit.Runs
import CollatzLean.Collatz2.Orbit.RunDefect
import CollatzLean.Collatz2.Orbit.RealizationRecovery
import CollatzLean.Collatz2.Orbit.OddOrbit
import CollatzLean.Collatz2.Orbit.FutureMinimum
import CollatzLean.Collatz2.Orbit.FutureMinimumArithmetic
import CollatzLean.Collatz2.Orbit.FutureMinimumSelection

import CollatzLean.Collatz2.Geometry.Center
import CollatzLean.Collatz2.Geometry.PrimitiveForm
import CollatzLean.Collatz2.Geometry.CyclicCenter
import CollatzLean.Collatz2.Geometry.RankPath
import CollatzLean.Collatz2.Geometry.RankUnit
import CollatzLean.Collatz2.Geometry.RankStrip
import CollatzLean.Collatz2.Geometry.RankQuotient
import CollatzLean.Collatz2.Geometry.ContractingPairDescent
import CollatzLean.Collatz2.Geometry.BestUpperSlope
import CollatzLean.Collatz2.Geometry.PrimitiveBestUpper
import CollatzLean.Collatz2.Geometry.WeightedRankSum
import CollatzLean.Collatz2.Geometry.WeightedRankFerrers
import CollatzLean.Collatz2.Geometry.WeightedRankBaseline
import CollatzLean.Collatz2.Geometry.ResidueIndexedFerrers
import CollatzLean.Collatz2.Geometry.RankUnitGeometricInverse
import CollatzLean.Collatz2.Geometry.ResidueIndexedFerrersCellSum
import CollatzLean.Collatz2.Geometry.ValidRecordRealization
import CollatzLean.Collatz2.Geometry.PrimitiveReducedChristoffelBridge
/-
# Collatz2 Geometry: 臨界 Ferrers 3進分離 A/B

臨界 Ferrers の 3進符号について、

* 補題A: 最初の相違列が符号差の exact 2進深さを決める。
* 補題B: `D = q * 3^r` のとき、その exact 2進深さが multiplier `q` へ移る。
* critical corridor: 最初の相違列 `j` と低い高さ `a` は `j <= a < criticalHeight j`。
* `|q| < 8` の場合: `q = ±4`, `a = 2`, `j = 2`, 高さは `(2,3)` または `(3,2)`。
-/
import CollatzLean.Collatz2.Geometry.CriticalFerrersThreeAdicCore
import CollatzLean.Collatz2.Geometry.CriticalFerrersThreeAdicSmallMultiplier
/-
# Collatz2 Geometry: 臨界 Ferrers 3進復元・次段階

1. actual word 上の有限区間 strict 増加と A/B wrapper
2. `3^s | start` から `3^(r+s)` anchor
3. valid 下端 / critical roof 上端 / width
4. width < `4*3^(r+s)` による一般復元
5. `s=0, r<=20` と `s=1, r<=53` の有限 corollary
-/

import CollatzLean.Collatz2.Geometry.CriticalFerrersThreeAdicActualWord
import CollatzLean.Collatz2.Geometry.CriticalFerrersThreeAdicAnchor
import CollatzLean.Collatz2.Geometry.CriticalFerrersThreeAdicRange
import CollatzLean.Collatz2.Geometry.CriticalFerrersThreeAdicReconstruction


import CollatzLean.Collatz2.Canonical.ResidueClass
import CollatzLean.Collatz2.Canonical.Representative
import CollatzLean.Collatz2.Canonical.CenterResidue
import CollatzLean.Collatz2.Canonical.Replay
import CollatzLean.Collatz2.Canonical.ReplayExtremality
import CollatzLean.Collatz2.Canonical.SwapResidue
import CollatzLean.Collatz2.Canonical.SwapCarry

import CollatzLean.Collatz2.Canonical.EndpointFundamentalBound
import CollatzLean.Collatz2.Canonical.PositiveSuffixBudget
import CollatzLean.Collatz2.Canonical.ZeroCoreSlack
import CollatzLean.Collatz2.Canonical.Q0Deep

import CollatzLean.Collatz2.Canonical.EndpointFloorCyclicGeometry
import CollatzLean.Collatz2.Canonical.EndpointFloorRankSeparation
import CollatzLean.Collatz2.Canonical.RotationRankTrap
import CollatzLean.Collatz2.Canonical.EndpointFloorTailRankTrap
import CollatzLean.Collatz2.Canonical.EndpointFloorBestUpperReduction
import CollatzLean.Collatz2.Canonical.EndpointFloorRecordDescent
import CollatzLean.Collatz2.Canonical.EndpointFloorRecordChain
import CollatzLean.Collatz2.Canonical.EndpointFloorWeightedRank
import CollatzLean.Collatz2.Canonical.EndpointFloorRankFerrers
import CollatzLean.Collatz2.Canonical.EndpointFloorFerrersInverse
import CollatzLean.Collatz2.Canonical.EndpointFloorFerrersClosedForm

import CollatzLean.Collatz2.Global.EndpointFloorNaturalCoordinates
import CollatzLean.Collatz2.Canonical.PrefixBudgetExcess
import CollatzLean.Collatz2.Canonical.DualSigmaBudget
import CollatzLean.Collatz2.Canonical.BudgetGapDifference
import CollatzLean.Collatz2.Canonical.SuffixBudgetLinearLower
import CollatzLean.Collatz2.Canonical.ZeroCoreCanonicalSlacks
import CollatzLean.Collatz2.Canonical.PrependOneSwapSeparation
import CollatzLean.Collatz2.Canonical.ZeroCoreSwapDefect

import CollatzLean.Collatz2.Arithmetic.ExponentSlope
import CollatzLean.Collatz2.External.TwoThreeGap
import CollatzLean.Collatz2.External.TwoThreeEffectiveGap
import CollatzLean.Collatz2.Canonical.ZeroCoreDualGap
import CollatzLean.Collatz2.Canonical.ZeroCoreNestedCorridor

import CollatzLean.Collatz2.Global.AdjacentTransferChain
import CollatzLean.Collatz2.Global.AdjacentCanonical
import CollatzLean.Collatz2.Global.SignDichotomy
import CollatzLean.Collatz2.Global.UnboundedReduction
import CollatzLean.Collatz2.Global.CenterEscape
import CollatzLean.Collatz2.Global.MovingCenter
import CollatzLean.Collatz2.Global.PrimitiveCenter
import CollatzLean.Collatz2.Global.PrimitiveReturnGap

import CollatzLean.Collatz2.Global.InfiniteSurvival
import CollatzLean.Collatz2.Global.OddOrbitSurvivalBridge
import CollatzLean.Collatz2.Global.RightBranchFirstCrossing
import CollatzLean.Collatz2.Global.RightBranchZeroReplay
import CollatzLean.Collatz2.Global.RightBranchZeroReplayMatveev
import CollatzLean.Collatz2.Global.CanonicalAdjacentContractingReturn
import CollatzLean.Collatz2.Global.RightBranchAdjacentReduction
import CollatzLean.Collatz2.Global.CanonicalEndpointFloorContractingReturn
import CollatzLean.Collatz2.Global.RightBranchEndpointFloorClosure

import CollatzLean.Collatz2.Mountain.Block
import CollatzLean.Collatz2.Mountain.OneMountainExclusion
import CollatzLean.Collatz2.Mountain.FiniteHercher
import CollatzLean.Collatz2.Mountain.FiniteHercherNarrow
import CollatzLean.Collatz2.Arithmetic.HercherContinuedFractionCertificate
import CollatzLean.Collatz2.External.BarinaHercher
import CollatzLean.Collatz2.Mountain.BarinaHercherLower
import CollatzLean.Collatz2.Mountain.PolynomialStartBound
import CollatzLean.Collatz2.Mountain.PolynomialMountainLower

import CollatzLean.Collatz2.Native.IntervalReplay
import CollatzLean.Collatz2.Native.BiCanonical
import CollatzLean.Collatz2.Native.PrependOneDefect
import CollatzLean.Collatz2.Native.ReplayDynamics
import CollatzLean.Collatz2.Native.AdjacentPrependOne

import CollatzLean.Collatz2.Matrix.Representation
import CollatzLean.Collatz2.Matrix.DefectGeometry
import CollatzLean.Collatz2.Matrix.Commutator
import CollatzLean.Collatz2.Matrix.FixedPoint
import CollatzLean.Collatz2.Matrix.CenterTransport
import CollatzLean.Collatz2.Matrix.ProjectiveDynamics

import CollatzLean.Collatz2.Arithmetic.KappaSwapValuation
import CollatzLean.Collatz2.Arithmetic.KappaBoundarySignature
import CollatzLean.Collatz2.Arithmetic.TwoThreeSmallGap
import CollatzLean.Collatz2.External.MatveevInput

import CollatzLean.Collatz2.ObstructionAudit.ObstructionAudit
import CollatzLean.Collatz2.ObstructionAudit.ExactWordTranslation
import CollatzLean.Collatz2.ObstructionAudit.CanonicalResidueAudit
import CollatzLean.Collatz2.ObstructionAudit.ExactTranslationConsequences
import CollatzLean.Collatz2.ObstructionAudit.FutureMinimumPrefixFloor
import CollatzLean.Collatz2.ObstructionAudit.TranslationShadowAudit

-- Record/Ferrers micro--macro general layer
import CollatzLean.Collatz2.RecordFerrers
-- current A -> generic Record/Ferrers bridge
import CollatzLean.Collatz2.Canonical.EndpointFloorRecordFactorizationBridge
-- primitive-reduced current A -> valid local micro packet -> genuine recovery
import CollatzLean.Collatz2.Canonical.EndpointFloorValidRecordMicroBridge

--CSTMicro
import CollatzLean.Collatz2.CSTMicro.Path
import CollatzLean.Collatz2.CSTMicro.Affine
import CollatzLean.Collatz2.CSTMicro.Residue
import CollatzLean.Collatz2.CSTMicro.MicroObject
import CollatzLean.Collatz2.CSTMicro.PolynomialCapacity
import CollatzLean.Collatz2.CSTMicro.InversePathSum
import CollatzLean.Collatz2.CSTMicro.AdjacentFerrersSwap
import CollatzLean.Collatz2.CSTMicro.ResidueCarry
import CollatzLean.Collatz2.CSTMicro.SmallRepresentativeCarry
import CollatzLean.Collatz2.CSTMicro.FerrersChain
import CollatzLean.Collatz2.CSTMicro.FirstPassagePreservation
import CollatzLean.Collatz2.CSTMicro.FirstFailureExtraction
import CollatzLean.Collatz2.CSTMicro.CarryCorridorExtraction
import CollatzLean.Collatz2.CSTMicro.SturmianHeight
import CollatzLean.Collatz2.CSTMicro.BinaryFerrersOrder
import CollatzLean.Collatz2.CSTMicro.FerrersBoundarySturmian
import CollatzLean.Collatz2.CSTMicro.BeattyPositions
import CollatzLean.Collatz2.CSTMicro.CriticalCrossingIndex
import CollatzLean.Collatz2.CSTMicro.BoundaryXiTruncation
import CollatzLean.Collatz2.CSTMicro.FirstFailureProvenance

--CSTMicro/ExternalArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.LopezStollPacket
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ChristoffelHeightSqueeze
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.DenominatorWindowCover
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalIntegerResidueSeparation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.LopezStollInstantiation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ChristoffelHeightBound
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.TwoLogDyadicSlack
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BoundaryACandidate
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongDenominatorWindowCover
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongBoundaryMatch
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongTwoLogDyadicSlack
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongBoundaryAClosure
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalContinuedFractionData
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalChristoffelPacket
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ChristoffelWronskian
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CorrectedChristoffelWronskian
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ChristoffelDefectValuation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianStrongOverlap
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalFiniteXiIdentity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalStrongMatchConstruction
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalContinuedFractionOrientation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalChristoffelPacketClosure
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBeattyConvergentCorridor
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianFiniteScanIdentity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalStrongMatchProof
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalChristoffelHeightFour
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinTwoThreeGap14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinStrongSlackStartNine
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalASteps6to8
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerFarey
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerFareyGeometry
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerFareyBeatty
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinLinearForm14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualRhinStrongSlack
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualCriticalFiniteScan
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualBoundaryFiniteCheck1538
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualBoundaryAFromRhin

--CSTMicro/CarryGeometry
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FirstFailureFareyGeometry
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FirstFailureFareyExtraction
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.NormalizedDefectCrossing
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.WeightedRankSmallResidueBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.NormalizedFerrersCocycle
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.NormalizedFerrersLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ActualBoundaryFirstFailureCocycle
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.CanonicalRepresentativeTrace
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ActualBoundaryFirstFailureCocycle
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ExactNormalizedFerrersLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ActualABExactCellLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FerrersCellResiduePotential
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.SafePrefixExactCellFirstPassage
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.SafePrefixCarryClearance
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.MinimalBadFirstPassage
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.MinimalActualABObstructionPacket
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.MinimalBadPredecessorGeometry
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.MinimalBadCellCostObstruction
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.BoundaryRespectingCellSlack
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.PositiveCostFerrersPotential
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.BoundaryRespectingRankCellBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ThreeQSmallStrip
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.GeneralPredecessorRankCellBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FirstPassagePredecessorRankDepth
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FerrersStepRankTransport
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RankCellInsertionCost
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RelativeRankCellCostLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.WeightedRankGlobalCostBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.UniversalCutWeight
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RankTopWinding
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.LocalRankTopLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.DiscountedThreeQStrip
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.UniversalRankTopFerrersStep
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FerrersStepRankTopLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RankTopChainWindingLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ResidualRankTopLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ExtraDepthFerrersTransport
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.CriticalBoundaryExtraDepth
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.FerrersColumnOccupancy
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ColumnLayerFareyBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.CriticalColumnLayerFareyBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ColumnProfileResidualLedger
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.MarkedFinalColumnCellPacket
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ColumnLayerCostDynamics
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.AdmissibleSturmianProfile
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ProfileCostClosedForm
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.SturmianProfileLevelSets
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.MaximalProfileLayerIntervals
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPrefixOstrowski
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalIntervalAffineDefect
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualOstrowskiBlockDecomposition
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBProfileDefectBridge
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBProfileBlockReduction
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ProfileIntervalCostBlocks
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RestrictedOstrowskiIntervals
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBeattyCurrentCorridor
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalIntervalPhasePeriodicity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ShiftedCorrectedChristoffelDictionary

-- terminal critical Record / Xi / polylog closure (1 + 2 + 3)
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.TerminalCriticalRecord
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalState
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinRecordPublic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalPolylog

-- origin full-depth exclusion -> maximal arithmetic critical tail -> one terminal polylog window
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBIntegralCriticalTail
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBFullDepthOriginExclusion
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBIntegralTailPolylog

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBShiftedWronskianElimination
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBShiftedDefectStateIdentities
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBProfileNumeratorValuation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalCoreValuation

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalCoreRightCarry
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalCoreRightCarryChain
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalLastDepthParity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalDepthTwoCarryModSix
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTopCellPredecessor
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTopCellDeltaB
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBActualProfileCoordinateBridge
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTopCellActualPredecessor
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTopCellMinimalityPacket

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBExposedPredecessorIndex
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBExposedPredecessorRealization
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalExposedCorner
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBPositiveComponentEndpoint
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleExposedCornerRigidity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerTerminalCore
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBAffineCornerTelescope
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBUniversalWeightCornerTelescope

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerSmallRootReduction
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLeftSmallRoot
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerRightShiftedSmallRoot

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerStrongXiPort
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLargeMReduction
/-
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerFiniteArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerFiniteBridge
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerSafetyAssembly
-/
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerBeattyTwoStep
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerDepthMonotone
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLayerSuffix
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerTopLayerWidth
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerTopCellCongruence

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBRelativeSuffixFullDepth
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBEndpointStateDefect
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBRelativeShiftedDictionaryOdd
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBRelativeShiftedDictionaryEven
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBRelativeShiftedStateCollapse
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBRelativeIntegralStateWronskian
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBRelativeChristoffelDefectValuation
-- Stage 8 legacy / diagnostic archive
--
-- `PureBCriticalizationStartDyadicRigidity` は
-- full Q-jump を得るために
--   beattyIndex criticalizationStart < criticalPowerQ j
-- を要求していた旧 Stage 8。
--
-- `PureBGoodScaleCounterexample` は arbitrary-phase への
-- full-precision 移植が成立しないことを記録する diagnostic counterexample。
--
-- 両ファイルとも証明史・反例記録として保存するが、
-- live proof route からは意図的に除外する。
--
-- import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBCriticalizationStartDyadicRigidity
-- import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBGoodScaleCounterexample

-- Stage 8R: residual dyadic rigidity
-- full-precision 仮定を要求せず、phase loss 後に残る dyadic precision を使う。
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ExtendedCriticalBeattyPhaseShift
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBResidualLocalWronskian
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBCriticalizationStartResidualDyadicRigidity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBeattyLocalSquares
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianSquareWindow14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBLocalSquareRigidity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTailLog14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalInitialSquareBand
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerPGapGrowth14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianSquareWindow14FromBHZ
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTailLog14FromBHZ

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualXiFiniteCheck118
--
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerActualLeftPrefix
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerCriticalizationRun
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLeftLocalizationLog14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerStrongLeftReadyGeometry
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLog14StrongClosure
--BHZ
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBHZIndexing
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalShiftBHZOstrowskiBridge
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalPhaseCoordinates
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalPrefixPowerCandidate
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalIntegerOrbitConjugacy
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalInterceptDigitIdentification
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalShiftSAdicSemanticsFromOdometer
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalProposition33Port
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalPrefixPowerSquare
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBeattyIncrementWord
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZFiniteWordMorphisms
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalStandardSemistandardWords
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalProposition33FromWordFormula
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalProposition33MorphismStage
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalPhaseDigitUniqueness


import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalProposition33ActualStage

import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalDigitResidualArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalLocalSquareSelector
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerPGapGrowth2744
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianSquareWindowD
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianSquareWindow2744FromBHZ
--
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBeattyOneShortSquares
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalOneShortPower
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalResidualFloor
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalOneShortSelector
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianOneShortSquareWindowD
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianOneShortSquareWindow196FromBHZ
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBLocalOneShortSquareRigidity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTailLog196
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLog196StrongClosure

-- exact BHZ denominator を最後まで保持する live route
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BHZCriticalOneShortSelectorExact
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBTerminalTailExactOneShort
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerExactBHZWidth

-- card=1: exact finite bands + eventual 196 fallback -> m >= 6466 closure
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerExactBHZFiniteBands
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerLog196EventualThreshold
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerCardOne6466
/-
-- card=1 finite residue: whole-run dyadic reduction + sharp local target + defect recurrence
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerWholeRunDyadic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerFiniteWidth112
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerDefectRecurrence
-/
-- card=1 finite side: entrance Xi freeze -> b < 116, m <= 2270
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerEntranceXi
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerEntranceXiFinite

-- card=1 finite residue: bounded Hensel scanner -> complete single-corner closure
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerFiniteHenselScan
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.PureBSingleCornerCardOneClosure

--純算術
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.MonotoneSuffixHenselChain
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.MonotoneSuffixHenselRepeatArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BeattyFactorRepeat
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BeattyCyclicCarryArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.MonotoneSuffixHenselZeroCycleArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.TwoThreeCycleDenominator
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.MonotoneSuffixHenselFinite36
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseMonotoneHenselChain
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseMonotoneHenselRepeatArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseMonotoneHenselZeroRepeatArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BeattyCycleIntervalBridge
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseScaledDifferenceShift
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.IntegralCriticalIntervalDefectStateDiff
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseMonotoneHenselLeftExtension
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseMonotoneHenselAdjacentReturn
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.FreeBaseMonotoneHenselTerminalReturn

--
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.EffectiveWindingResidualBound
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualPureBEffectiveWindingBridge
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.QuantitativeBoundaryAResidualBound
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RecordFerrersResidualCoarsening
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RecordFerrersEffectiveWindingBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RecordFerrersZeroStartSanity
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.RecordFerrersGenericStartCoarsening
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.IntervalFerrersDeficitCostBridge
import CollatzLean.Collatz2.CSTMicro.CarryGeometry.ColumnLayerScaledExactIntervalRealization



import CollatzLean.Collatz2.RecordFerrers.All


import CollatzLean.Collatz2.CSTMicro.MultiCorner.MultiCorner




set_option linter.style.header false

/-!
# Collatz2

旧 `CollatzLean.Collatz.*` に依存しない独立再構築の入口。
既存 current-A / mountain / obstruction AMinimalBadFirstPassageI に加え、`RecordFerrers` で
current-A 非依存の record/Ferrers/affine factorization 一般層を公開する。
-/
