import CollatzLean.Collatz2.Core.Word
import CollatzLean.Collatz2.Core.AffineTransfer
import CollatzLean.Collatz2.Core.DisplacementForm
import CollatzLean.Collatz2.Core.TranslationPath
import CollatzLean.Collatz2.Core.Realization
import CollatzLean.Collatz2.Core.Interval

import CollatzLean.Collatz2.Local.DeterminantSign
import CollatzLean.Collatz2.Local.Defect
import CollatzLean.Collatz2.Local.FirstCrossing
import CollatzLean.Collatz2.Local.SuffixDeterminantProfile
import CollatzLean.Collatz2.Local.TranslationDeterminant
import CollatzLean.Collatz2.Local.ContractingClosure

import CollatzLean.Collatz2.Orbit.Runs
import CollatzLean.Collatz2.Orbit.RunDefect
import CollatzLean.Collatz2.Orbit.RealizationRecovery
import CollatzLean.Collatz2.Orbit.OddOrbit
import CollatzLean.Collatz2.Orbit.FutureMinimum
import CollatzLean.Collatz2.Orbit.FutureMinimumArithmetic
import CollatzLean.Collatz2.Orbit.FutureMinimumSelection

import CollatzLean.Collatz2.Geometry.Center
import CollatzLean.Collatz2.Geometry.PrimitiveForm
import CollatzLean.Collatz2.Geometry.CyclicCenter
import CollatzLean.Collatz2.Geometry.RankPath
import CollatzLean.Collatz2.Geometry.RankUnit
import CollatzLean.Collatz2.Geometry.RankStrip
import CollatzLean.Collatz2.Geometry.RankQuotient
import CollatzLean.Collatz2.Geometry.ContractingPairDescent
import CollatzLean.Collatz2.Geometry.BestUpperSlope
import CollatzLean.Collatz2.Geometry.PrimitiveBestUpper
import CollatzLean.Collatz2.Geometry.WeightedRankSum
import CollatzLean.Collatz2.Geometry.WeightedRankFerrers
import CollatzLean.Collatz2.Geometry.WeightedRankBaseline
import CollatzLean.Collatz2.Geometry.ResidueIndexedFerrers
import CollatzLean.Collatz2.Geometry.RankUnitGeometricInverse
import CollatzLean.Collatz2.Geometry.ResidueIndexedFerrersCellSum
import CollatzLean.Collatz2.Geometry.ValidRecordRealization
import CollatzLean.Collatz2.Geometry.PrimitiveReducedChristoffelBridge

import CollatzLean.Collatz2.Canonical.ResidueClass
import CollatzLean.Collatz2.Canonical.Representative
import CollatzLean.Collatz2.Canonical.CenterResidue
import CollatzLean.Collatz2.Canonical.Replay
import CollatzLean.Collatz2.Canonical.ReplayExtremality
import CollatzLean.Collatz2.Canonical.SwapResidue
import CollatzLean.Collatz2.Canonical.SwapCarry

import CollatzLean.Collatz2.Canonical.EndpointFundamentalBound
import CollatzLean.Collatz2.Canonical.PositiveSuffixBudget
import CollatzLean.Collatz2.Canonical.ZeroCoreSlack
import CollatzLean.Collatz2.Canonical.Q0Deep

import CollatzLean.Collatz2.Canonical.EndpointFloorCyclicGeometry
import CollatzLean.Collatz2.Canonical.EndpointFloorRankSeparation
import CollatzLean.Collatz2.Canonical.RotationRankTrap
import CollatzLean.Collatz2.Canonical.EndpointFloorTailRankTrap
import CollatzLean.Collatz2.Canonical.EndpointFloorBestUpperReduction
import CollatzLean.Collatz2.Canonical.EndpointFloorRecordDescent
import CollatzLean.Collatz2.Canonical.EndpointFloorRecordChain
import CollatzLean.Collatz2.Canonical.EndpointFloorWeightedRank
import CollatzLean.Collatz2.Canonical.EndpointFloorRankFerrers
import CollatzLean.Collatz2.Canonical.EndpointFloorFerrersInverse
import CollatzLean.Collatz2.Canonical.EndpointFloorFerrersClosedForm

import CollatzLean.Collatz2.Global.EndpointFloorNaturalCoordinates
import CollatzLean.Collatz2.Canonical.PrefixBudgetExcess
import CollatzLean.Collatz2.Canonical.DualSigmaBudget
import CollatzLean.Collatz2.Canonical.BudgetGapDifference
import CollatzLean.Collatz2.Canonical.SuffixBudgetLinearLower
import CollatzLean.Collatz2.Canonical.ZeroCoreCanonicalSlacks
import CollatzLean.Collatz2.Canonical.PrependOneSwapSeparation
import CollatzLean.Collatz2.Canonical.ZeroCoreSwapDefect

import CollatzLean.Collatz2.Arithmetic.ExponentSlope
import CollatzLean.Collatz2.External.TwoThreeGap
import CollatzLean.Collatz2.External.TwoThreeEffectiveGap
import CollatzLean.Collatz2.Canonical.ZeroCoreDualGap
import CollatzLean.Collatz2.Canonical.ZeroCoreNestedCorridor

import CollatzLean.Collatz2.Global.AdjacentTransferChain
import CollatzLean.Collatz2.Global.AdjacentCanonical
import CollatzLean.Collatz2.Global.SignDichotomy
import CollatzLean.Collatz2.Global.UnboundedReduction
import CollatzLean.Collatz2.Global.CenterEscape
import CollatzLean.Collatz2.Global.MovingCenter
import CollatzLean.Collatz2.Global.PrimitiveCenter
import CollatzLean.Collatz2.Global.PrimitiveReturnGap

import CollatzLean.Collatz2.Global.InfiniteSurvival
import CollatzLean.Collatz2.Global.OddOrbitSurvivalBridge
import CollatzLean.Collatz2.Global.RightBranchFirstCrossing
import CollatzLean.Collatz2.Global.RightBranchZeroReplay
import CollatzLean.Collatz2.Global.RightBranchZeroReplayMatveev
import CollatzLean.Collatz2.Global.CanonicalAdjacentContractingReturn
import CollatzLean.Collatz2.Global.RightBranchAdjacentReduction
import CollatzLean.Collatz2.Global.CanonicalEndpointFloorContractingReturn
import CollatzLean.Collatz2.Global.RightBranchEndpointFloorClosure

import CollatzLean.Collatz2.Mountain.Block
import CollatzLean.Collatz2.Mountain.OneMountainExclusion
import CollatzLean.Collatz2.Mountain.FiniteHercher
import CollatzLean.Collatz2.Mountain.FiniteHercherNarrow
import CollatzLean.Collatz2.Arithmetic.HercherContinuedFractionCertificate
import CollatzLean.Collatz2.External.BarinaHercher
import CollatzLean.Collatz2.Mountain.BarinaHercherLower
import CollatzLean.Collatz2.Mountain.PolynomialStartBound
import CollatzLean.Collatz2.Mountain.PolynomialMountainLower

import CollatzLean.Collatz2.Native.IntervalReplay
import CollatzLean.Collatz2.Native.BiCanonical
import CollatzLean.Collatz2.Native.PrependOneDefect
import CollatzLean.Collatz2.Native.ReplayDynamics
import CollatzLean.Collatz2.Native.AdjacentPrependOne

import CollatzLean.Collatz2.Matrix.Representation
import CollatzLean.Collatz2.Matrix.DefectGeometry
import CollatzLean.Collatz2.Matrix.Commutator
import CollatzLean.Collatz2.Matrix.FixedPoint
import CollatzLean.Collatz2.Matrix.CenterTransport
import CollatzLean.Collatz2.Matrix.ProjectiveDynamics

import CollatzLean.Collatz2.Arithmetic.KappaSwapValuation
import CollatzLean.Collatz2.Arithmetic.KappaBoundarySignature
import CollatzLean.Collatz2.Arithmetic.TwoThreeSmallGap
import CollatzLean.Collatz2.External.MatveevInput

import CollatzLean.Collatz2.ObstructionAudit.ObstructionAudit
import CollatzLean.Collatz2.ObstructionAudit.ExactWordTranslation
import CollatzLean.Collatz2.ObstructionAudit.CanonicalResidueAudit
import CollatzLean.Collatz2.ObstructionAudit.ExactTranslationConsequences
import CollatzLean.Collatz2.ObstructionAudit.FutureMinimumPrefixFloor
import CollatzLean.Collatz2.ObstructionAudit.TranslationShadowAudit

-- Record/Ferrers micro--macro general layer
import CollatzLean.Collatz2.RecordFerrers
-- current A -> generic Record/Ferrers bridge
import CollatzLean.Collatz2.Canonical.EndpointFloorRecordFactorizationBridge
-- primitive-reduced current A -> valid local micro packet -> genuine recovery
import CollatzLean.Collatz2.Canonical.EndpointFloorValidRecordMicroBridge

--CSTMicro
import CollatzLean.Collatz2.CSTMicro.Path
import CollatzLean.Collatz2.CSTMicro.Affine
import CollatzLean.Collatz2.CSTMicro.Residue
import CollatzLean.Collatz2.CSTMicro.MicroObject
import CollatzLean.Collatz2.CSTMicro.PolynomialCapacity
import CollatzLean.Collatz2.CSTMicro.InversePathSum
import CollatzLean.Collatz2.CSTMicro.AdjacentFerrersSwap
import CollatzLean.Collatz2.CSTMicro.ResidueCarry
import CollatzLean.Collatz2.CSTMicro.SmallRepresentativeCarry
import CollatzLean.Collatz2.CSTMicro.FerrersChain
import CollatzLean.Collatz2.CSTMicro.FirstPassagePreservation
import CollatzLean.Collatz2.CSTMicro.FirstFailureExtraction
import CollatzLean.Collatz2.CSTMicro.CarryCorridorExtraction
import CollatzLean.Collatz2.CSTMicro.SturmianHeight
import CollatzLean.Collatz2.CSTMicro.BinaryFerrersOrder
import CollatzLean.Collatz2.CSTMicro.FerrersBoundarySturmian
import CollatzLean.Collatz2.CSTMicro.BeattyPositions
import CollatzLean.Collatz2.CSTMicro.CriticalCrossingIndex
import CollatzLean.Collatz2.CSTMicro.BoundaryXiTruncation

--CSTMicro/ExternalArithmetic
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.LopezStollPacket
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ChristoffelHeightSqueeze
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.DenominatorWindowCover
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalIntegerResidueSeparation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.LopezStollInstantiation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ChristoffelHeightBound
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.TwoLogDyadicSlack
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.BoundaryACandidate
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongDenominatorWindowCover
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongBoundaryMatch
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongTwoLogDyadicSlack
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.StrongBoundaryAClosure
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalContinuedFractionData
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalChristoffelPacket
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianStrongOverlap
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalFiniteXiIdentity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalStrongMatchConstruction
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalContinuedFractionOrientation
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalChristoffelPacketClosure
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalBeattyConvergentCorridor
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalSturmianFiniteScanIdentity
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalStrongMatchProof
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalChristoffelHeightFour
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinTwoThreeGap14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinStrongSlackStartNine
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalASteps6to8
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerFarey
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerFareyGeometry
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.CriticalPowerFareyBeatty
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.RhinLinearForm14
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualRhinStrongSlack
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualCriticalFiniteScan
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualBoundaryFiniteCheck1538
import CollatzLean.Collatz2.CSTMicro.ExternalArithmetic.ActualBoundaryAFromRhin


set_option linter.style.header false

/-!
# Collatz2

旧 `CollatzLean.Collatz.*` に依存しない独立再構築の入口。
既存 current-A / mountain / obstruction API に加え、`RecordFerrers` で
current-A 非依存の record/Ferrers/affine factorization 一般層を公開する。
-/
