import CollatzLean.CollatzSecondLayer.ChainReduction

/-!
# 隣接chain・rotation drift経路の監査

公開する新しい型と還元定理を固定する。
未証明プレースホルダーを導入せず、公開APIだけを監査する。
-/

namespace CollatzSecondLayer

#check CoherentC3CylinderSequence
#check coherentCylinderUpgrade_of_arithmetic
#check InfiniteOrderedTerminalChain
#check InfiniteOrderedTerminalChain.ofCoherent
#check OrderedDifferenceData
#check HasPersistentChainAlternative
#check EventuallyChainSpecialData
#check persistentAlternative_or_eventuallySpecial
#check SynchronizationCarrySequence
#check SynchronizationCarrySequence.syncLength_tendsto_of_depth_bounded
#check ChainSynchronizationLaw
#check chainSynchronizationLawOfEventuallySpecial
#check RotationSourceData
#check RotationNormalizedData
#check eventually_rotation_normalized
#check BoundedDepthLongSyncRotationData
#check RecordBlockCompressionData
#check RecordBlockCompressionData.totalExact
#check RotationDriftStaircaseData
#check RecordBlockCompressionPrinciple
#check unbounded_orbit_chain_reduction
#check no_unbounded_orbit_of_chain_exclusions

end CollatzSecondLayer
