import CollatzLean.Collatz2.RecordFerrers.Perturbation.P01BoundaryExcess
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P02BoundaryExcessRecurrence
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P03BoundaryExcessClosedForm
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P04CarryBoundaryCharacterization
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P05SpliceLocality
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P06FerrersCoordinateLocality
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P07FixedSkeletonDistanceAdditivity
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P08AdjacentTransferCarrySupport
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P09OneBitDefectLaw
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P10PersistentExcess
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P11OldBoundaryDestruction
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P12BoundaryExcessMonotonicity
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P13PermanentOldBoundaryFailure
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P14RoofContactSaturation
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P15CanonicalRepairCut
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P16PrimitiveReducedChristoffelRepair
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P17FirstFundamentalStripReturn
import CollatzLean.Collatz2.RecordFerrers.Perturbation.P18DefectPhaseBridge

/-!
# Record–Ferrers 摂動理論 1–18

1–11 では fixed-skeleton locality、一ビット欠陥、旧境界破壊を構築する。
12–17 では欠陥後の単調性から canonical repair cut、Christoffel 座標、
fundamental rank strip への最初の復帰まで進める。
18 では欠陥側の二値 carry 位相と repair 側の有限剰余位相を結び、
局所欠陥と clearance 飽和を同じ位相言語へ翻訳する。
-/
