import CollatzLean.CollatzSecondLayer2

/-!
# CollatzSecondLayer2公開API監査

既存raw三分岐、source-preserving強化三分岐、無条件outcome分解、
first-deferred四段階refinement、eventual-syncからmeanderへの実定理、
および完全に無条件となったrefined三分岐を監査する。
-/

namespace CollatzSecondLayer2

#check PolynomialBelowTwoPower
#check TwoThreeGapPolynomialBound
#check OddOrbit
#check OddOrbit.futureMinimumSequence
#check MovingFirstCrossingData
#check OddOrbit.WindowDifferenceData
#check OddOrbit.CapturedWindowAt
#check OddOrbit.SynchronizedWindowAt
#check OddOrbit.DeferredWindowAt
#check OddOrbit.CapturedWindowAt.nextDifferenceData
#check OddOrbit.SynchronizedWindowAt.nextDifferenceData
#check OddOrbit.FiniteCaptureNormalizationData
#check OddOrbit.InfiniteCaptureNormalizationData
#check OddOrbit.captureNormalizationFromWindowOutcome_nonempty
#check PolynomialPreparedFullWindowFamily
#check polynomialPreparedFullWindowFamily
#check PreparedCaptureNormalizationTowerData
#check PolynomialPreparedFullWindowFamily.normalizationTower
#check AnchoredOneSidedMeanderData
#check PolynomialSpecialC3TowerData

-- 既存raw第三枝
#check NormalizationGeneratedObstructionTowerData
#check NormalizationGeneratedObstructionTowerData.captureGap_pos
#check NormalizationGeneratedObstructionTowerData.nextDifference
#check PolynomialPreparedFullWindowFamily.toNormalizationGeneratedObstructionTower
#check persistentCapture_to_normalizationObstruction
#check preparedFullWindow_positive_dichotomy
#check unboundedOrbit_positive_trichotomy_on
#check unbounded_odd_orbit_positive_trichotomy
#check no_unbounded_odd_orbit_of_positive_exclusions

-- 標準構成由来を保持する強化版第三枝
#check StandardNormalizationGeneratedObstructionTowerData
#check StandardNormalizationGeneratedObstructionTowerData.forget
#check standardNormalizationObstructionOfPersistent
#check standardPreparedFullWindow_positive_dichotomy
#check unboundedOrbit_standard_positive_trichotomy_on
#check unbounded_odd_orbit_standard_positive_trichotomy
#check standardNormalization_implies_raw

-- refinement局所算術
#check movingFullWindowPreparation_windowTwoSteps_eq
#check firstCrossing_threePow_lt_twoPow
#check firstCrossing_twoPow_le_succ_mul_threePow
#check OddOrbit.CapturedWindowAt.windowTwoSteps_add_captureGap_eq
#check StandardNormalizationGeneratedObstructionTowerData.initial_threePow_lt_twoPow
#check StandardNormalizationGeneratedObstructionTowerData.initial_twoPow_le_succ_mul_threePow
#check OddOrbit.FiniteCaptureNormalizationData.terminalPacket
#check firstDeferredTerminalOutcome_nonempty
#check DeferredPreparedWindowOutcome.endpoint_large_or_special

-- 無条件outcome tower分解
#check FirstDeferredNormalizationTowerData
#check EventuallySynchronizedNormalizationTowerData
#check standardNormalization_outcomeTower_dichotomy

-- first-deferred四段階refinement
#check PolynomialTerminalFirstDeferredTowerData
#check PolynomialTerminalFirstDeferredTowerData.toPolynomialSpecialC3Tower
#check NoCriticalCaptureInFirstDeferred
#check OddOrbit.FiniteCaptureNormalizationData.twoPow_captureCount_lt_succ
#check FirstDeferredNormalizationTowerData.twoPow_captureCount_lt_windowLength_succ
#check OddOrbit.FiniteCaptureNormalizationData.exists_synchronizedPlateau_of_mul_le_terminalTime
#check SuperPolynomialNoCriticalFirstDeferredTowerData
#check SuperPolynomialNoCriticalFirstDeferredTowerData.toLongSynchronizedPlateauTower
#check firstDeferred_subsequence_classification
#check firstDeferredTower_refinement

-- critical captureのstrict派生事実
#check CriticalCaptureInFirstDeferred.windowLength_pos
#check CriticalCaptureInFirstDeferred.afterExpanding

-- eventual-syncからactual meanderへの実定理
#check ExpWord.expanding_append
#check OddOrbit.segmentWord_add_period_eq
#check firstCrossing_length_le_of_exponent_period
#check meanderAt_of_exponent_period_of_large_futureMinimum
#check OddOrbit.InfiniteCaptureNormalizationData.exponent_period_at_synchronizedTail
#check EventuallySynchronizedNormalizationTowerData.toAnchoredOneSidedMeanderData
#check eventuallySynchronizedTower_to_meander
#check EventuallySynchronizedTowerToMeanderPrinciple
#check eventuallySynchronizedTowerToMeanderPrinciple

-- 最終残余二構造と無条件refined還元
#check CriticalCaptureTowerData
#check LongSynchronizedPlateauTowerData
#check RefinedNormalizationObstructionTowerData
#check standardNormalization_refinement
#check standardNormalization_residual_of_exclusions
#check unboundedOrbit_refined_positive_trichotomy_on
#check unboundedOrbit_refined_positive_quadrichotomy_on
#check unbounded_odd_orbit_refined_positive_trichotomy
#check no_unbounded_odd_orbit_of_refined_positive_exclusions

end CollatzSecondLayer2
