import CollatzLean.CollatzSecondLayer2

/-!
# CollatzSecondLayer2公開API監査

旧`CollatzSecondLayer`、補集合的第三枝、未証明解析principleに依存せず、
三つの正対象への無条件還元を監査する。
-/

namespace CollatzSecondLayer2

#check PolynomialBelowTwoPower
#check TwoThreeGapPolynomialBound
#check OddOrbit
#check OddOrbit.futureMinimumSequence
#check MovingFirstCrossingData
#check OddOrbit.WindowDifferenceData
#check OddOrbit.CapturedWindowAt
#check OddOrbit.SynchronizedWindowAt
#check OddOrbit.DeferredWindowAt
#check OddOrbit.CapturedWindowAt.nextDifferenceData
#check OddOrbit.SynchronizedWindowAt.nextDifferenceData
#check OddOrbit.FiniteCaptureNormalizationData
#check OddOrbit.InfiniteCaptureNormalizationData
#check OddOrbit.captureNormalizationFromWindowOutcome_nonempty
#check PolynomialPreparedFullWindowFamily
#check polynomialPreparedFullWindowFamily
#check PreparedCaptureNormalizationTowerData
#check PolynomialPreparedFullWindowFamily.normalizationTower
#check AnchoredOneSidedMeanderData
#check PolynomialSpecialC3TowerData
#check NormalizationGeneratedObstructionTowerData
#check NormalizationGeneratedObstructionTowerData.captureGap_pos
#check NormalizationGeneratedObstructionTowerData.nextDifference
#check PolynomialPreparedFullWindowFamily.toNormalizationGeneratedObstructionTower
#check persistentCapture_to_normalizationObstruction
#check preparedFullWindow_positive_dichotomy
#check unboundedOrbit_positive_trichotomy_on
#check unbounded_odd_orbit_positive_trichotomy
#check no_unbounded_odd_orbit_of_positive_exclusions

end CollatzSecondLayer2
