import CollatzLean.CollatzSecondLayer2.PositiveReduction

/-!
# 非有界odd-only軌道の無条件な正の三分岐

公開する第三対象は、persistent captureからactualに構成された
normalization outcome towerである。旧marked-prefix第三枝と、
未証明の解析的四分岐principleは主還元から削除する。
-/

namespace CollatzSecondLayer2

#check NormalizationGeneratedObstructionTowerData
#check preparedFullWindow_positive_dichotomy
#check unboundedOrbit_positive_trichotomy_on
#check unbounded_odd_orbit_positive_trichotomy
#check no_unbounded_odd_orbit_of_positive_exclusions

end CollatzSecondLayer2
