import CollatzLean.Collatz.AdjacentReturn.IntegerObstruction.Basic
import CollatzLean.Collatz.AdjacentReturn.IntegerObstruction.Expanding
import CollatzLean.Collatz.AdjacentReturn.IntegerObstruction.FirstCrossing
import CollatzLean.Collatz.AdjacentReturn.IntegerObstruction.Contracting
import CollatzLean.Collatz.AdjacentReturn.IntegerObstruction.Global
