import CollatzLean.CollatzFirstLayer.CanonicalReplay
import CollatzLean.CollatzFirstLayer.CarrySynchronization
import CollatzLean.CollatzFirstLayer.TerminalConsequences

import CollatzLean.CollatzSecondLayer.InfiniteOrbit
import CollatzLean.CollatzSecondLayer.FutureMinimum
import CollatzLean.CollatzSecondLayer.MovingCompactness
import CollatzLean.CollatzSecondLayer.MovingCompactnessConsequences
import CollatzLean.CollatzSecondLayer.LimitWord
import CollatzLean.CollatzSecondLayer.FirstCrossing
import CollatzLean.CollatzSecondLayer.C3Cylinder
import CollatzLean.CollatzSecondLayer.CylinderUpgradeProof
import CollatzLean.CollatzSecondLayer.CylinderConsequences
import CollatzLean.CollatzSecondLayer.InfiniteTerminal
import CollatzLean.CollatzSecondLayer.InfiniteBranches
import CollatzLean.CollatzSecondLayer.SpecialC3
import CollatzLean.CollatzSecondLayer.Reduction
--import CollatzLean.CollatzSecondLayer.Audit
