import CollatzLean.Collatz.Arithmetic.Growth
import CollatzLean.Collatz.External.TwoThreeGap
import CollatzLean.Collatz.TwoAdic.Factorization
import CollatzLean.Collatz.TwoAdic.Valuation
import CollatzLean.Collatz.Word.Basic
import CollatzLean.Collatz.Word.Affine
import CollatzLean.Collatz.Word.Center
import CollatzLean.Collatz.Word.Replay
import CollatzLean.Collatz.Word.Kernel
import CollatzLean.Collatz.Word.KernelValuation
import CollatzLean.Collatz.Word.Geometry
import CollatzLean.Collatz.Word.Contracting
import CollatzLean.Collatz.Word.SharpAffine
import CollatzLean.Collatz.Word.Periodic
import CollatzLean.Collatz.OneStep.Carry
import CollatzLean.Collatz.FiniteOrbit.Runs
import CollatzLean.Collatz.FiniteOrbit.Reconstruction
import CollatzLean.Collatz.FiniteOrbit.Comparison
import CollatzLean.Collatz.FiniteOrbit.Trajectory
import CollatzLean.Collatz.Canonical.Residue
import CollatzLean.Collatz.Canonical.Runs
import CollatzLean.Collatz.Canonical.Replay
import CollatzLean.Collatz.Canonical.Cylinder
import CollatzLean.Collatz.Canonical.CylinderDerived
import CollatzLean.Collatz.Canonical.CylinderDynamics
import CollatzLean.Collatz.Canonical.FirstCrossingReduction
import CollatzLean.Collatz.OddOrbit.Basic
import CollatzLean.Collatz.OddOrbit.Periodic
import CollatzLean.Collatz.OddOrbit.HighExponent
import CollatzLean.Collatz.OddOrbit.FutureMinimum
import CollatzLean.Collatz.OddOrbit.Selection
import CollatzLean.Collatz.OddOrbit.StandardFutureMinimum
import CollatzLean.Collatz.OddOrbit.StandardSelection
import CollatzLean.Collatz.OddOrbit.FutureMinimumArithmetic
import CollatzLean.Collatz.OddOrbit.FutureMinimumLocal
import CollatzLean.Collatz.Selection.Cofinal
import CollatzLean.Collatz.AdjacentReturn.Basic
import CollatzLean.Collatz.AdjacentReturn.Geometry
import CollatzLean.Collatz.AdjacentReturn.Bounds
import CollatzLean.Collatz.AdjacentReturn.Valuation
import CollatzLean.Collatz.AdjacentReturn.FirstCrossing
import CollatzLean.Collatz.AdjacentReturn.FirstCrossingArithmetic
import CollatzLean.Collatz.AdjacentReturn.FirstHigh
import CollatzLean.Collatz.AdjacentReturn.FirstCrossingBridge
import CollatzLean.Collatz.AdjacentReturn.CanonicalLate
import CollatzLean.Collatz.AdjacentReturn.CanonicalLatePacket
import CollatzLean.Collatz.AdjacentReturn.Dichotomy
import CollatzLean.Collatz.AdjacentReturn.StrongContractingTail
import CollatzLean.Collatz.AdjacentReturn.FullBlockCanonical
import CollatzLean.Collatz.AdjacentReturn.CanonicalContractingChain
import CollatzLean.Collatz.AdjacentReturn.GapDepthDichotomy
import CollatzLean.Collatz.AdjacentReturn.IntegerObstruction
import CollatzLean.Collatz.Main
