import CollatzLean.CollatzSecondLayer2.Arithmetic
import CollatzLean.CollatzSecondLayer2.AffineTransport
import CollatzLean.CollatzSecondLayer2.DirectAffineTransport
import CollatzLean.CollatzSecondLayer2.InfiniteOrbit
import CollatzLean.CollatzSecondLayer2.PeriodicExponent
import CollatzLean.CollatzSecondLayer2.FutureMinimum
import CollatzLean.CollatzSecondLayer2.FirstCrossing
import CollatzLean.CollatzSecondLayer2.FirstCrossingPolynomial
import CollatzLean.CollatzSecondLayer2.TwoAdicShell
import CollatzLean.CollatzSecondLayer2.CaptureWindow
import CollatzLean.CollatzSecondLayer2.CaptureNormalization
import CollatzLean.CollatzSecondLayer2.CaptureNormalizationFromWindow
import CollatzLean.CollatzSecondLayer2.SpecialC3
import CollatzLean.CollatzSecondLayer2.WindowAnalysis
import CollatzLean.CollatzSecondLayer2.Synchronization
import CollatzLean.CollatzSecondLayer2.AlternativeExclusion
import CollatzLean.CollatzSecondLayer2.CaptureRefinement
import CollatzLean.CollatzSecondLayer2.TransportRefinement
import CollatzLean.CollatzSecondLayer2.PositivePreparation
import CollatzLean.CollatzSecondLayer2.PositiveObjects
import CollatzLean.CollatzSecondLayer2.PreparedNormalizationTower
import CollatzLean.CollatzSecondLayer2.NormalizationObstruction
import CollatzLean.CollatzSecondLayer2.PositiveReduction
import CollatzLean.CollatzSecondLayer2.NormalizationRefinementSource
import CollatzLean.CollatzSecondLayer2.NormalizationRefinementFacts
import CollatzLean.CollatzSecondLayer2.NormalizationOutcomeSplit
import CollatzLean.CollatzSecondLayer2.NormalizationRefinementObjects
import CollatzLean.CollatzSecondLayer2.PolynomialTerminalRefinement
import CollatzLean.CollatzSecondLayer2.CaptureCountRefinement
import CollatzLean.CollatzSecondLayer2.LongPlateauRefinement
import CollatzLean.CollatzSecondLayer2.FirstDeferredSubsequenceClassification
import CollatzLean.CollatzSecondLayer2.FirstDeferredRefinement
import CollatzLean.CollatzSecondLayer2.EventuallySynchronizedRefinement
import CollatzLean.CollatzSecondLayer2.NormalizationRefinement
import CollatzLean.CollatzSecondLayer2.RefinedPositiveReduction
import CollatzLean.CollatzSecondLayer2.ContractingWindowBounds
import CollatzLean.CollatzSecondLayer2.NoCriticalDiscountedSpecialC3
import CollatzLean.CollatzSecondLayer2.FirstCriticalTransition
import CollatzLean.CollatzSecondLayer2.FinalPositiveReduction
--import CollatzLean.CollatzSecondLayer2.Reduction

/-!
# CollatzSecondLayer2

旧`CollatzSecondLayer`をimportせず、第一層のみから再構成した第二層。

## 算術入力

固定多項式が`2^(p+1)`より遅く成長する`PolynomialBelowTwoPower`は
mathlibの漸近定理からLean内で証明済みである。

外部の算術入力として残るのは、2と3の相対gapに対する
`TwoThreeGapPolynomialBound`だけである。

## 無条件raw還元

非有界odd-only軌道を、補集合を含まない次の三対象へ無条件に還元する。

* `AnchoredOneSidedMeanderData`
* `PolynomialSpecialC3TowerData`
* `NormalizationGeneratedObstructionTowerData`

## source-preserving refinement

標準preparation由来を保持する`StandardNormalizationGeneratedObstructionTowerData`も
非有界軌道から無条件に構成され、既存raw第三対象へ忘却できる。

強化版towerは無条件に

* `FirstDeferredNormalizationTowerData`
* `EventuallySynchronizedNormalizationTowerData`

へ分解される。eventual-sync側は周期指数tailを生むため直接矛盾する。

first-deferred側では、従来のlong plateauを最終対象にせず、その生成元である
super-polynomial no-critical towerからscaled endpoint上界付きterminal Special C3を
構成する。persistent critical側は各項の最初のcritical時刻をcanonicalに選び直す。

## 最終三分岐

`TwoThreeGapPolynomialBound`のもとで、非有界odd-only軌道は無条件に

* `AnchoredOneSidedMeanderData`
* `SpecialC3ObstructionTowerData`
  * `PolynomialSpecialC3TowerData`
  * `DiscountedSpecialC3TowerData`
* `FirstCriticalTransitionTowerData`

へ還元される。

first-critical枝はさらに

* `LargeExpandingDefectTransitionTowerData`
* `CaptureDenseTransitionTowerData`
* `TerminalSpecialC3TransitionTowerData`

へ無条件に分かれる。terminal Special C3は中央枝へ吸収せず、独立した内部枝として残す。

既存の`CriticalCaptureTowerData`、`LongSynchronizedPlateauTowerData`、
`RefinedNormalizationObstructionTowerData`は互換APIおよび中間診断対象として残す。
-/
