import CollatzLean.CollatzWindowCore.Carry
import CollatzLean.CollatzWindowCore.Normalization
import CollatzLean.CollatzWindowCore.NormalizationFromWindow
import CollatzLean.CollatzWindowCore.SpecialC3
import CollatzLean.CollatzWindowCore.Analysis
import CollatzLean.CollatzWindowCore.Synchronization
