import CollatzLean.Collatz.Arithmetic.Growth
import CollatzLean.Collatz.External.TwoThreeGap
import CollatzLean.Collatz.TwoAdic.Factorization
import CollatzLean.Collatz.Word.Basic
import CollatzLean.Collatz.Word.Affine
import CollatzLean.Collatz.Word.Center
import CollatzLean.Collatz.Word.Replay
import CollatzLean.Collatz.Word.Kernel
import CollatzLean.Collatz.Word.Geometry
import CollatzLean.Collatz.OneStep.Carry
import CollatzLean.Collatz.FiniteOrbit.Runs
import CollatzLean.Collatz.FiniteOrbit.Comparison
import CollatzLean.Collatz.FiniteOrbit.Trajectory
import CollatzLean.Collatz.Canonical.Residue
import CollatzLean.Collatz.Canonical.Runs
import CollatzLean.Collatz.OddOrbit.Basic
import CollatzLean.Collatz.OddOrbit.FutureMinimum
import CollatzLean.Collatz.OddOrbit.Selection
import CollatzLean.Collatz.Selection.Cofinal
import CollatzLean.Collatz.AdjacentReturn.Basic
import CollatzLean.Collatz.AdjacentReturn.Dichotomy
import CollatzLean.Collatz.Main
