import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.ChordRank
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordPartition
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordPartitionInverse
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordRoofBridge
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordTie
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.CanonicalRecordChain
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.CanonicalCarryExact
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordFerrers
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.LinearGauge
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.MechanicalPhase
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.FractionalGauge
set_option linter.style.header false
