import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.ChordRank
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordPartition
import CollatzLean.Collatz3.Experimental2.GenericRecordFerrers.RecordRoofBridge
set_option linter.style.header false
